name:                localize
version:             0.3.0.0
github:              "eunikolsky/localize"
license:             BSD3
author:              "Eugene Nikolsky"
maintainer:          "e@egeek.me"
copyright:           "2022 Eugene Nikolsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eunikolsky/localize#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- text

library:
  source-dirs: src
  dependencies:
  - megaparsec

executables:
  localize:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - localize
    - aeson-pretty
    - containers
    - deepseq
    - directory
    - filepath
    - fsnotify

tests:
  localize-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - localize
    - raw-strings-qq
    - tasty
    - tasty-hunit
